### ISSUE TITLE
Truncated incorrect DOUBLE value

### ISSUE THREAD

**Issue by PJH-Eric** [videokojot/EFCore.BulkExtensions.MIT#85]
https://github.com/borisdj/EFCore.BulkExtensions/issues/1309

**Comment by videokojot** [comment]
Thank for the report, I will try to replicate and fix it.

**Comment by videokojot** [comment]
I created replication scenario in branch fix/issue-85 . The exception I am running into is: "Can't reopen table: 'ServersTemp104c918fOutput'" , I will need to fix it, probably by using the CTE , see: https://dev.mysql.com/doc/refman/8.0/en/temporary-table-problems.html 

Then I can get to the truncated problem.

**Comment by videokojot** [comment]
I finally got to it, I discovered it is due to the wrong logic for SetOutputIdentoty for MySQL. I created separate issue for that. See: https://github.com/videokojot/EFCore.BulkExtensions.MIT/issues/90

> The logic for getting the output identity for MySQL have several flaws:
does not get the idenity for the udpated rows (problem when updating by custom columns)
key must be identity,
key must be numeric,
possible race condition (the output identity might be affected by other sql statements running at the server))
**For now, the resolution is not to use SetOutputIdentity for MySql at all as it does not work (reliably) anyway.**
